### PR TITLE
Update/corrections docs, free voip setup

### PR DESCRIPTION
**Pull request by fryguy100**
refresh/update,for text to speech, remove unused, added some nessary freepbx modules, have SSL cert point to webmin

Update Dockerfile

build bug fixes and remove not needed

Update Dockerfile

force rebuild, try fix freepbx unkown build error, maybe because of SSL conf adding

Update Dockerfile

Update Dockerfile

Update Dockerfile

Update containerstartup.sh

update/refresh - adding faxing ability, use postfix for mail, and DNS service

build bug fixes, removing Issabel-pbx repo

build fix - Include avantfax from  sourceforge.net

some corrections

Update Dockerfile

Update Dockerfile

Update Dockerfile

Update Dockerfile

Add preset modem to avantfax databas, setup email to fax, some corrections

reorder fax setup startup

update/corrections

Update Dockerfile

Update README.md

Update README.md

additional Obi setup setting

### CODE REVIEW

**Comment by TheTechsTech** [comment]
What problem where you having? 

I might need to update/refresh the docker image. I use the voip system daily, the image I run internally updated itself, I haven't had an issue to check image after last build pass and started correctly.

**Comment by fryguy100** [comment]
I seem to be having an issue with running a new image. I can access webmin, though the freepbx admin page won't pull up. According to webmin none of the services are started, and they cannot be started. FWConsole appears to not be running either. 

Sorry about this. I'm still very new to github and pressed pull accidentally. I thought I could try forking the image, rolling it back to a previous commit and seeing if that image would work. Though if you think you'll update the image I think I'll wait, since you actually know what you're doing. 

Anyways, if you care to take a look, here are the container logs. 

[freepbx log.txt](https://github.com/techno-express/freepbx/files/7772492/freepbx.log.txt)

**Comment by TheTechsTech** [comment]
What is the docker command you using to start up the image?

Did you edit the systemctl.py file or any systemd service file?

The first line in your log is the problem, and maybe any systemd service file created.

You might want to build/compile image locally see if it builds correctly, I ended up doing that before sending it to docker hub registry for building.

**Comment by fryguy100** [comment]
I used this command, and have used it in the past with success:
docker run --name freepbx \
-v freepbx-etc:/etc \
-v freepbx-www:/var/www \
-v freepbx-log:/var/log \
-v freepbx-lib:/var/lib \
-v freepbx-home:/home \
-v /etc/resolv.conf:/etc/resolv.conf:ro \
--cap-add=NET_ADMIN --net=kansas_data \
--ip=192.168.25.20 --hostname=kpbx \
--restart=always -itd technoexpress/freepbx

kansas_data is my macvlan. 

I also tried using this command on a new test device with a new docker setup last night, and it did the same thing.
docker run --name freepbx \
-v freepbx-etc:/etc \
-v freepbx-www:/var/www \
-v freepbx-log:/var/log \
-v freepbx-lib:/var/lib \
-v freepbx-home:/home \
-v /etc/resolv.conf:/etc/resolv.conf:ro \
--cap-add=NET_ADMIN --net=host \
--hostname=kpbx \
--restart=always -itd technoexpress/freepbx

I didn't edit the systemd file in anyway. I'll look into building/compiling it locally. I've never done that before.

**Comment by TheTechsTech** [comment]
It's not going to build correctly, some repos no longer have some of the rpm's needed. 

I just upgraded my docker hub account they no longer grab pushes from GitHub without doing so.

My remote server for some reason not liking my ssh keys can't connect to do local build. So for  now updating GitHub files then checking build status on docker hub.

**Comment by TheTechsTech** [comment]
I have refreshed the image build passing now, had to remove the hylafax setup stuff for now, conflicting repo rpm versions. 

If you ever get your build environment setup. Try changing Php to 7.4 and FreePBX to 16. There new version require 7.4. 

Also the nodejs needs to updated current version in build has security vulnerable from docker scanner security check run. The version in image was there cause something wouldn't install without it. Not sure about now, probably fixed now. 

I will try updating by next weekend or so. I'm to worried about making changes on current system and missing calls.

**Pull request closed without merging**
